fix cluster folder

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -19,6 +19,9 @@ jobs:
       DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: "1" # Enable color output, even though the console output is redirected in Actions
       TERM: xterm # Enable color output in GitHub Actions
     steps:
+    - name: Start Redis Services (docker-compose)
+      working-directory: ./tests/RedisConfigs
+      run: docker compose -f docker-compose.yml up -d --wait   
     - name: Checkout code
       uses: actions/checkout@v4
       with:
@@ -31,9 +34,6 @@ jobs:
           8.0.x
     - name: .NET Build
       run: dotnet build Build.csproj -c Release /p:CI=true
-    - name: Start Redis Services (docker-compose)
-      working-directory: ./tests/RedisConfigs
-      run: docker compose -f docker-compose.yml up -d --wait
     - name: StackExchange.Redis.Tests
       run: dotnet test tests/StackExchange.Redis.Tests/StackExchange.Redis.Tests.csproj -c Release --logger trx --logger GitHubActions --results-directory ./test-results/ /p:CI=true
     - uses: dorny/test-reporter@v1
@@ -62,6 +62,7 @@ jobs:
         distribution: Ubuntu-22.04
     - name: Install Redis
       shell: wsl-bash {0}
+      working-directory: ./tests/RedisConfigs
       run: |
         sudo apt-get update
         sudo apt-get install curl gpg lsb-release libgomp1 jq -y
@@ -69,41 +70,39 @@ jobs:
         tar xf redis-stack.tar.gz
     - name: Run redis-server
       shell: wsl-bash {0}
-      working-directory: ./tests/RedisConfigs
+      working-directory: ./tests/RedisConfigs/redis-stack-server-7.4.0-v2
       run: |
         pwd
         ls .
-        # Create required temporary directory
-        mkdir -p ../Temp
         # Run each server instance in order
-        ../../redis-stack-server-7.4.0-v2/bin/redis-stack-server ./Basic/primary-6379-3.0.conf &
-        ../../redis-stack-server-7.4.0-v2/bin/redis-stack-server ./Basic/replica-6380.conf &
-        ../../redis-stack-server-7.4.0-v2/bin/redis-stack-server ./Basic/secure-6381.conf &
-        ../../redis-stack-server-7.4.0-v2/bin/redis-stack-server ./Failover/primary-6382.conf &
-        ../../redis-stack-server-7.4.0-v2/bin/redis-stack-server ./Failover/replica-6383.conf &
-        ../../redis-stack-server-7.4.0-v2/bin/redis-stack-server ./Cluster/cluster-7000.conf --dir ./Cluster &
-        ../../redis-stack-server-7.4.0-v2/bin/redis-stack-server ./Cluster/cluster-7001.conf --dir ./Cluster &
-        ../../redis-stack-server-7.4.0-v2/bin/redis-stack-server ./Cluster/cluster-7002.conf --dir ./Cluster &
-        ../../redis-stack-server-7.4.0-v2/bin/redis-stack-server ./Cluster/cluster-7003.conf --dir ./Cluster &
-        ../../redis-stack-server-7.4.0-v2/bin/redis-stack-server ./Cluster/cluster-7004.conf --dir ./Cluster &
-        ../../redis-stack-server-7.4.0-v2/bin/redis-stack-server ./Cluster/cluster-7005.conf --dir ./Cluster &
-        ../../redis-stack-server-7.4.0-v2/bin/redis-stack-server ./Sentinel/redis-7010.conf &
-        ../../redis-stack-server-7.4.0-v2/bin/redis-stack-server ./Sentinel/redis-7011.conf &
-        ../../redis-stack-server-7.4.0-v2/bin/redis-stack-server ./Sentinel/sentinel-26379.conf --sentinel &
-        ../../redis-stack-server-7.4.0-v2/bin/redis-stack-server ./Sentinel/sentinel-26380.conf --sentinel &
-        ../../redis-stack-server-7.4.0-v2/bin/redis-stack-server ./Sentinel/sentinel-26381.conf --sentinel &
+        # .bin/redis-stack-server ../Basic/primary-6379-3.0.conf &
+        # .bin/redis-stack-server ../Basic/replica-6380.conf &
+        # .bin/redis-stack-server ../Basic/secure-6381.conf &
+        # .bin/redis-stack-server ../Failover/primary-6382.conf &
+        # .bin/redis-stack-server ../Failover/replica-6383.conf &
+        .bin/redis-stack-server ../Cluster/cluster-7000.conf --dir ../Cluster &
+        .bin/redis-stack-server ../Cluster/cluster-7001.conf --dir ../Cluster &
+        .bin/redis-stack-server ../Cluster/cluster-7002.conf --dir ../Cluster &
+        .bin/redis-stack-server ../Cluster/cluster-7003.conf --dir ../Cluster &
+        .bin/redis-stack-server ../Cluster/cluster-7004.conf --dir ../Cluster &
+        .bin/redis-stack-server ../Cluster/cluster-7005.conf --dir ../Cluster &
+        # .bin/redis-stack-server ../Sentinel/redis-7010.conf &
+        # .bin/redis-stack-server ../Sentinel/redis-7011.conf &
+        # .bin/redis-stack-server ../Sentinel/sentinel-26379.conf --sentinel &
+        # .bin/redis-stack-server ../Sentinel/sentinel-26380.conf --sentinel &
+        # .bin/redis-stack-server ../Sentinel/sentinel-26381.conf --sentinel &
         # Wait for server instances to get ready
         sleep 5
-        echo "Checking redis-server version with port 6379"
-        ../../redis-stack-server-7.4.0-v2/bin/redis-cli -p 6379 INFO SERVER | grep redis_version || echo "Failed to get version for port 6379"
-        echo "Checking redis-server version with port 6380"
-        ../../redis-stack-server-7.4.0-v2/bin/redis-cli -p 6380 INFO SERVER | grep redis_version || echo "Failed to get version for port 6380"
-        echo "Checking redis-server version with port 6381"
-        ../../redis-stack-server-7.4.0-v2/bin/redis-cli -p 6381 INFO SERVER | grep redis_version || echo "Failed to get version for port 6381"
-        echo "Checking redis-server version with port 6382"
-        ../../redis-stack-server-7.4.0-v2/bin/redis-cli -p 6382 INFO SERVER | grep redis_version || echo "Failed to get version for port 6382"
-        echo "Checking redis-server version with port 6383"
-        ../../redis-stack-server-7.4.0-v2/bin/redis-cli -p 6383 INFO SERVER | grep redis_version || echo "Failed to get version for port 6383"
+        # echo "Checking redis-server version with port 6379"
+        # ../../redis-stack-server-7.4.0-v2/bin/redis-cli -p 6379 INFO SERVER | grep redis_version || echo "Failed to get version for port 6379"
+        # echo "Checking redis-server version with port 6380"
+        # ../../redis-stack-server-7.4.0-v2/bin/redis-cli -p 6380 INFO SERVER | grep redis_version || echo "Failed to get version for port 6380"
+        # echo "Checking redis-server version with port 6381"
+        # ../../redis-stack-server-7.4.0-v2/bin/redis-cli -p 6381 INFO SERVER | grep redis_version || echo "Failed to get version for port 6381"
+        # echo "Checking redis-server version with port 6382"
+        # ../../redis-stack-server-7.4.0-v2/bin/redis-cli -p 6382 INFO SERVER | grep redis_version || echo "Failed to get version for port 6382"
+        # echo "Checking redis-server version with port 6383"
+        # ../../redis-stack-server-7.4.0-v2/bin/redis-cli -p 6383 INFO SERVER | grep redis_version || echo "Failed to get version for port 6383"
         echo "Checking redis-server version with port 7000"
         ../../redis-stack-server-7.4.0-v2/bin/redis-cli -p 7000 INFO SERVER | grep redis_version || echo "Failed to get version for port 7000"
         echo "Checking redis-server version with port 7001"
@@ -116,16 +115,16 @@ jobs:
         ../../redis-stack-server-7.4.0-v2/bin/redis-cli -p 7004 INFO SERVER | grep redis_version || echo "Failed to get version for port 7004"
         echo "Checking redis-server version with port 7005"
         ../../redis-stack-server-7.4.0-v2/bin/redis-cli -p 7005 INFO SERVER | grep redis_version || echo "Failed to get version for port 7005"
-        echo "Checking redis-server version with port 7010"
-        ../../redis-stack-server-7.4.0-v2/bin/redis-cli -p 7010 INFO SERVER | grep redis_version || echo "Failed to get version for port 7010"
-        echo "Checking redis-server version with port 7011"
-        ../../redis-stack-server-7.4.0-v2/bin/redis-cli -p 7011 INFO SERVER | grep redis_version || echo "Failed to get version for port 7011"
-        echo "Checking redis-server version with port 26379"
-        ../../redis-stack-server-7.4.0-v2/bin/redis-cli -p 26379 INFO SERVER | grep redis_version || echo "Failed to get version for port 26379"
-        echo "Checking redis-server version with port 26380"
-        ../../redis-stack-server-7.4.0-v2/bin/redis-cli -p 26380 INFO SERVER | grep redis_version || echo "Failed to get version for port 26380"
-        echo "Checking redis-server version with port 26381"
-        ../../redis-stack-server-7.4.0-v2/bin/redis-cli -p 26381 INFO SERVER | grep redis_version || echo "Failed to get version for port 26381"
+        # echo "Checking redis-server version with port 7010"
+        # ../../redis-stack-server-7.4.0-v2/bin/redis-cli -p 7010 INFO SERVER | grep redis_version || echo "Failed to get version for port 7010"
+        # echo "Checking redis-server version with port 7011"
+        # ../../redis-stack-server-7.4.0-v2/bin/redis-cli -p 7011 INFO SERVER | grep redis_version || echo "Failed to get version for port 7011"
+        # echo "Checking redis-server version with port 26379"
+        # ../../redis-stack-server-7.4.0-v2/bin/redis-cli -p 26379 INFO SERVER | grep redis_version || echo "Failed to get version for port 26379"
+        # echo "Checking redis-server version with port 26380"
+        # ../../redis-stack-server-7.4.0-v2/bin/redis-cli -p 26380 INFO SERVER | grep redis_version || echo "Failed to get version for port 26380"
+        # echo "Checking redis-server version with port 26381"
+        # ../../redis-stack-server-7.4.0-v2/bin/redis-cli -p 26381 INFO SERVER | grep redis_version || echo "Failed to get version for port 26381"
       continue-on-error: true
 
     - name: .NET Build
